spring:
  datasource:
    url: jdbc:postgresql://localhost/patate?user=sa&password=Pass@word
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    mapping-resources:
      - "axon/DeadLetterEventEntry.hbm.xml"
      - "axon/DomainEventEntry.hbm.xml"
      - "axon/SagaEntry.hbm.xml"
      - "axon/SnapshotEventEntry.hbm.xml"
      - "axon/TokenEntry.hbm.xml"
#    properties:
#      hibernate:
#        dialect: com.example.oidtypeconversion.ByteaSQLDialect

axon:
  axon server:
    enabled: false
  serializer:
    events: jackson
    general: jackson
    messages: jackson
server:
  port: 7777
logging:
  level:
    root: info
